# Same as pipewire.conf.d/10-gilgamesh-vm.conf, for PulseAudio apps.
pulse.properties.rules = [
  { matches = [ { cpu.vm.name = !null } ]
    actions = { update-props = { pulse.min.quantum = 256/48000 } } }
]
